### ISSUE TITLE
Blog post challenge: Write something about remark42

### ISSUE THREAD

**Issue by openscript** [SemiShogun/nectoj.ninja#11]
As I have now 2 blog posts I challenge you to write something about:
https://github.com/umputun/remark42

You are allowed to take revenge. Have fun 🤠

**Comment by SemiShogun** [comment]
Challenge accepted 😎

**Comment by SemiShogun** [comment]
Took a while, but I finally managed to write a few things about remark42. 
https://nectoj.ninja/blog/2021-08-07-how-to-use-remark42-and-my-experience-with-it

After publishing this post, I realised how badly my blog needs to be renovated😬(it'll be upgraded soon)
If you want, I can give you a markdown version of it.

**Comment by openscript** [comment]
Great you did it! :1st_place_medal: 

I wish I could write this comment under your blog post, but maybe after the renovation is done?

Also I'm open to challenges over here https://github.com/openscript/obin.ch

**Comment by SemiShogun** [comment]
> 
> 
> Great you did it! 🥇
> 
> I wish I could write this comment under your blog post, but maybe after the renovation is done?
> 
> Also I'm open to challenges over here https://github.com/openscript/obin.ch

Haha sounds great 😂 Also I'm already working on the renovation so it shouldn't take too long.
While you're waiting, I challenge you to create a new blog post feature https://github.com/openscript/obin.ch/issues/22
